### ISSUE TITLE
etransfer branch works with etd::// fore jive5ab as source, but fails with file://

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/jive5ab#14]
Tried etransfer branch yesterday for etd:// transfers with m5opy. Worked fine. Then tried to start some file:// transfers that worked another day. Failed miserably. I tried 4 parallell transfers using one instance but different data ports. The problem was the etransfer branch of jive5ab on the sender side (m5copy was the same in both cases, and receiver was running jive5ab 2.9 in both cases). Behaviour was that two scans initially made it through, but then the jive5ab sender instance froze! I could not CTRL+C it, nor "kill" it. I had to use "kill -9" to terminate it. Restarted it, tried to resume my transfers, and instantly froze again. 

It was late, and I had data I needed to ship, so I used an older v3 version of jive5ab I had lying around, and that worked flawlessly. So, I'm sure the problem is tied to using file:// --> file:// transfers with the etransfer branche of jive5ab as source.

**Comment by haavee** [comment]
The problem was definitely not in `file://` --> `file://` transfers but in _many_ more (woops).
The deadlock was introduced by this patch https://github.com/jive-vlbi/jive5ab/commit/0b98e0dfbddc949a1992d05e8262dc3503855730 and fixed by https://github.com/jive-vlbi/jive5ab/commit/bc0c68a5812ff98743081bed5708fecd162a0a3c (partially undoes the patch)
