### ISSUE TITLE
how to listen multi NIC interface?

### ISSUE THREAD

**Issue by billchen0001** [jive-vlbi/jive5ab#32]
We found Jive5ab only capture one interface traffic, we want to capture four NIC e.g. eth0, eth1,eth2,eth3.
How to do it?

Many thanks,
Bill

**Comment by haavee** [comment]
Hi Bill, by default `jive5ab` listens on _all_ interfaces on the same (udp) port number (if you've configured it to record udp packets). The reason why it captures data from one interface only is due to the Linux kernel's routing/binding issues.

Most likely the four interfaces have been configured to have an IPv4 address from the same subnet and the same subnet mask. The kernel doesn't see the traffic from those four cards as coming from the same network and hence drops `n-1` traffic streams.

Because `jive5ab` operates completely at the (logical) IPv4 level, it is a matter of reconfiguring the interfaces' subnets to make sure they're different. The sending equipment must be configured to send to the different IPv4 addresses and then you'd be all set.

I've made an example for creating four subnet definitions and their settings here:
https://www.davidc.net/sites/default/subnets/subnets.html?network=192.168.0.0&mask=28&division=7.31

The usable IPs for the `eth[0..3]` cards would be 192.168.0.2, 192.168.0.6, etc; set the netmask as per the table.
If the sending equipment is directly connected I think you'd only need to change the destination address(es) to those IP addresses.

I might be able to request a working config from a station where I know they've done this - let me know.

**Comment by billchen0001** [comment]
@haavee  Thank you so much, it make sense , I will try to setup as you mentioned. 

Thanks again, Bill

**Comment by billchen0001** [comment]
@haavee 
It works with four NICs after we setup IP/Netmasks as you mentioned.

Thanks,
Bill
